Add files via upload
Batch size=10
Patch size = ?

change all training=False to training=True to tackle input shape mismatch on shape[0] and shape[4]

val_accuracy is unavailable

model.compiled_loss()` is deprecated. Instead, use `model.compute_loss(x, y, y_pred, sample_weight, training)

fresh pc restart to make sure the gpu memory is free

ValueError: not enough values to unpack (expected 3, got 2) this needs to be looked at again but it took a day to run all the epochs.