Add files via upload
ValueError: Shape mismatch in layer #1 (named stem_conv)for weight stem_conv/kernel. Weight expects shape (3, 3, 1, 32). Received saved weight with shape (3, 3, 3, 32)


Change the weights to None:

def get_cnn_model():
    base_model = efficientnet.EfficientNetB0(
        input_shape=(*IMAGE_SIZE, 3),
        include_top=False,
        weights=None,  #CHANGING THIS TO NONE FROM IMAGENET
    )

https://stackoverflow.com/questions/62739893/why-are-keras-models-instantiated-with-imagenet-weights-only

or set all layers to be trainable. 

For testing switching to None from imagenet is the easier option.